name: Bug Report
description: Report something that isn't working as expected
title: "[Bug] <short description>"
labels: [bug, needs-triage]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to identify and fix this issue efficiently.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in a clear and concise way.
      placeholder: "The login page throws an error when I click submit without entering credentials..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to /login  
        2. Click submit  
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The form should show a validation error instead of crashing."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, app version, or any relevant environment details.
      placeholder: |
        - OS: macOS 13.4
        - Browser: Chrome 123
        - API Version: v1.2.1

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Attach any logs, screenshots, or error messages that help explain the issue.

  - type: input
    id: related
    attributes:
      label: Related Issues (if any)
      placeholder: "#123"
